# Generated by Django 4.1.7 on 2023-03-22 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("questionnaire", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("balance", models.IntegerField(default=0)),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                (
                    "favorites",
                    models.ManyToManyField(
                        blank=True, to="questionnaire.service", verbose_name="Избранное"
                    ),
                ),
            ],
        ),
    ]
