# Generated by Django 4.1.7 on 2023-03-22 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("questionnaire", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="services",
                to="users.profile",
                verbose_name="Владелец анкеты",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="questionnaire.service",
            ),
        ),
        migrations.AddField(
            model_name="multipleimage",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="images",
                to="questionnaire.service",
            ),
        ),
        migrations.AddField(
            model_name="addition",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="questionnaire.category"
            ),
        ),
    ]
