# Generated by Django 4.1.7 on 2023-03-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="confirmed",
            field=models.BooleanField(default=False, verbose_name="Фото подтверждено"),
        ),
        migrations.AlterField(
            model_name="service",
            name="type",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Девушка"),
                    (2, "Массажистки"),
                    (3, "Парни"),
                    (4, "Фирма досуга"),
                ],
                max_length=10,
            ),
        ),
    ]
