# Generated by Django 4.1.7 on 2023-03-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0003_alter_service_confirmed_alter_service_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="nationality",
            field=models.CharField(default="123", max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="service",
            name="type",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Девушка"),
                    (2, "Массажистки"),
                    (3, "Парни"),
                    (4, "Фирма досуга"),
                ],
                verbose_name="Тип подписки",
            ),
        ),
    ]
