# Generated by Django 4.1.7 on 2023-03-28 11:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0004_service_nationality_alter_service_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="on_top",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Поднять анкету",
            ),
            preserve_default=False,
        ),
    ]
