# Generated by Django 4.1.7 on 2023-03-29 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0007_ontopprice_alter_service_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ontopprice",
            options={
                "verbose_name": "Стоимость Поднятия",
                "verbose_name_plural": "Стоимость Поднятия",
            },
        ),
        migrations.AddField(
            model_name="service",
            name="call_time_end",
            field=models.TimeField(
                default=datetime.time(23, 59), verbose_name="Звонить до"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="call_time_start",
            field=models.TimeField(
                default=datetime.time(0, 0), verbose_name="Звонить с"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="messanger",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WhatsApp", "WhatsApp"),
                    ("Viber", "Viber"),
                    ("Telegram", "Telegram"),
                ],
                max_length=20,
                null=True,
                verbose_name="Привязанный мессенджер",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="phone",
            field=models.CharField(
                default="+79999999999", max_length=20, verbose_name="Номер телефона"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="service",
            name="type",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Девушка"),
                    (2, "Массажистки"),
                    (3, "Парни"),
                    (4, "Фирма досуга"),
                ],
                verbose_name="Тип анкеты",
            ),
        ),
    ]
