# Generated by Django 4.1.7 on 2023-03-29 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0009_addition_price_alter_service_appearance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="additions",
            field=models.ManyToManyField(blank=True, to="questionnaire.addition"),
        ),
        migrations.AlterField(
            model_name="service",
            name="appearance",
            field=models.CharField(
                choices=[
                    ("", "выбрать..."),
                    ("Худая", "Худая"),
                    ("Стройная", "Стройная"),
                    ("Спортивная", "Спортивная"),
                    ("Полная", "Полная"),
                ],
                max_length=60,
                verbose_name="Телосложение",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(
                default="123",
                validators=[
                    django.core.validators.MinLengthValidator(
                        200, "Поле должно содержать минимум 200 символов"
                    )
                ],
                verbose_name="Описание",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="service",
            name="gender",
            field=models.CharField(
                choices=[
                    ("", "выбрать..."),
                    ("Натуралка/Натурал", "Натуралка/Натурал"),
                    ("Лесби/Гей", "Лесби/Гей"),
                    ("Би", "Би"),
                ],
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="hair",
            field=models.CharField(
                choices=[
                    ("", "выбрать..."),
                    ("Брюнетка", "Брюнетка"),
                    ("Шатенка", "Шатенка"),
                    ("Блондинка", "Блондинка"),
                    ("Рыжая", "Рыжая"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="messanger",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "выбрать..."),
                    ("WhatsApp", "WhatsApp"),
                    ("Viber", "Viber"),
                    ("Telegram", "Telegram"),
                ],
                max_length=20,
                null=True,
                verbose_name="Привязанный мессенджер",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="nationality",
            field=models.CharField(
                choices=[
                    ("", "выбрать..."),
                    ("Русская/Русский", "Русская/Русский"),
                    ("Украинка/Украинец", "Украинка/Украинец"),
                    ("Негритянка/Негр", "Негритянка/Негр"),
                    ("Мулатка/Мулат", "Мулатка/Мулат"),
                    ("Азиатка/Азиат", "Азиатка/Азиат"),
                    ("Кореянка/Кореец", "Кореянка/Кореец"),
                    ("Татарка/Татар", "Татарка/Татар"),
                    ("Казашка/Казах", "Казашка/Казах"),
                    ("Узбечка/Узбек", "Узбечка/Узбек"),
                ],
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="type",
            field=models.SmallIntegerField(
                choices=[
                    ("", "выбрать..."),
                    (1, "Девушка"),
                    (2, "Массажистки"),
                    (3, "Парни"),
                    (4, "Фирма досуга"),
                ],
                verbose_name="Тип анкеты",
            ),
        ),
    ]
