# Generated by Django 4.1.7 on 2023-04-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "questionnaire",
            "0010_alter_service_additions_alter_service_appearance_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="addition",
            name="price",
            field=models.IntegerField(default=0, verbose_name="Доплата за услугу"),
        ),
        migrations.AlterField(
            model_name="service",
            name="subscription",
            field=models.IntegerField(
                choices=[(30, "TOP тариф"), (20, "VIP тариф"), (10, "Базовый тариф")],
                default=10,
            ),
        ),
    ]
