# Generated by Django 4.1.7 on 2023-04-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0012_multipleimage_moderated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multipleimage",
            name="moderated",
            field=models.BooleanField(default=False, verbose_name="Фото проверено"),
        ),
    ]
