# Generated by Django 4.1.7 on 2023-04-03 14:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0013_alter_multipleimage_moderated"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="date_published",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата публикации",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="addition",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="questionnaire.category",
                verbose_name="Категория",
            ),
        ),
    ]
