# Generated by Django 4.1.7 on 2023-04-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0014_service_date_published_alter_addition_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="price_half_hour",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Експресс (30 мин)"
            ),
        ),
    ]
