# Generated by Django 4.0.6 on 2022-10-04 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='support',
            options={'ordering': ['topic'], 'verbose_name': 'Поддержка', 'verbose_name_plural': 'Топики'},
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='')),
                ('status', models.CharField(choices=[('O', 'open'), ('C', 'closed')], default='O', max_length=1, verbose_name='Статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Отправитель', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
