# Generated by Django 4.0.6 on 2022-10-04 15:42

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_support_options_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-status'], 'verbose_name': 'Обращение', 'verbose_name_plural': 'Обращения'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='slug', editable=False, populate_from='question', unique=True),
            preserve_default=False,
        ),
    ]
