# Generated by Django 4.0.6 on 2022-10-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_alter_ticket_answer_alter_ticket_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.SmallIntegerField(verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('wishes', models.TextField(blank=True, null=True, verbose_name='Пожелания')),
            ],
            options={
                'verbose_name': 'Отзыв о сайте',
                'verbose_name_plural': 'Отзывы о сайте',
                'ordering': ['rate'],
            },
        ),
    ]
