# Generated by Django 4.1.3 on 2022-12-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0007_sitereview_created_at_sitereview_created_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={
                "ordering": ["-status", "-created_at"],
                "verbose_name": "Обращение",
                "verbose_name_plural": "Обращения",
            },
        ),
        migrations.AlterField(
            model_name="sitereview",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
    ]
